sudo: required

language: generic

services:
  - docker

script:
  - docker build -t "dotfiles" -f Dockerfile --build-arg UID=$(id -u) --build-arg UNAME=$(id -un) .
  # enforce emojis on commits
  # test the install script
  - docker run -v"$(pwd):/mnt/workspace" -t dotfiles /bin/bash -c
    "
      cd /mnt/workspace &&
      py-commit-checker --emojis &&
      DOTFILES_INSTALL_ALL=y ./install
    "

  # pr builds, lint the commits
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    docker run -v"$(pwd):/mnt/workspace" -e TRAVIS_BRANCH -t dotfiles /bin/bash -c
    "
      cd /mnt/workspace &&
      PY_COMMIT_CHECKER_ARGS=--emojis py-commit-checker-branch origin/$TRAVIS_BRANCH
    "; fi'
