sudo: required

language: generic

services:
  - docker

script:
  # enforce emojis on commits
  # test the install script
  - docker build -t dotfiles-test .
  - docker run -v"$(pwd):/mnt/workspace" -t "dotfiles-test" /bin/bash -c
    "
      cd /mnt/workspace &&
      py-commit-checker --emojis &&
      INSTALL_VSCODE_EXT=1 ./install
    "
