name: main-ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # checkout v2, with recursive submodule update
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # build the Docker image we use to run the tests
      - name: test.sh
        run: ./test.sh
